//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC02a.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Carrito
    {
        public int RecordId { get; set; }
        public string CartId { get; set; }
        public int idproducto { get; set; }
        public int Count { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual producto producto { get; set; }
    }
}
