//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC02a.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class categoriaProd
    {
        public categoriaProd()
        {
            this.producto = new HashSet<producto>();
        }
    [Column("idcategoriaProd"), Key]
        public int idcategoriaProd { get; set; }
        public string descrip { get; set; }
    
        public virtual ICollection<producto> producto { get; set; }
    }
}
