//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC02a.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class estado
    {
        public estado()
        {
            this.Cliente = new HashSet<Cliente>();
            this.empleado = new HashSet<empleado>();
            this.opciones = new HashSet<opciones>();
            this.ordenProduccion = new HashSet<ordenProduccion>();
            this.pedido = new HashSet<pedido>();
            this.producto = new HashSet<producto>();
            this.Seguimiento = new HashSet<Seguimiento>();
        }
      [Column("idestado"), Key]
        public int idestado { get; set; }
        public string descrip { get; set; }
        public int cnPedido { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<empleado> empleado { get; set; }
        public virtual ICollection<opciones> opciones { get; set; }
        public virtual ICollection<ordenProduccion> ordenProduccion { get; set; }
        public virtual ICollection<pedido> pedido { get; set; }
        public virtual ICollection<producto> producto { get; set; }
        public virtual ICollection<Seguimiento> Seguimiento { get; set; }
    }
}
