//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC02a.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class insumo_proveedor
    {
        public int idProveedor { get; set; }
        public int idinsumo { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        public virtual insumo insumo { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
