//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC02a.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class insumo
    {
        public insumo()
        {
            this.insumo_proveedor = new HashSet<insumo_proveedor>();
            this.producto = new HashSet<producto>();
        }
     [Column("idinsumo"), Key]
        public int idinsumo { get; set; }
        public string nomInsumo { get; set; }
        public string stock { get; set; }
        public Nullable<System.DateTime> fechaVenc { get; set; }
        public int idtipo_medida { get; set; }
        public int idcategoriaIn { get; set; }
    
        public virtual categoriaIn categoriaIn { get; set; }
        public virtual tipo_medida tipo_medida { get; set; }
        public virtual ICollection<insumo_proveedor> insumo_proveedor { get; set; }
        public virtual ICollection<producto> producto { get; set; }
    }
}
