//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC02a.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class opciones
    {
        public opciones()
        {
            this.rol = new HashSet<rol>();
        }
     [Column("idopciones"), Key]
        public int idopciones { get; set; }
        public string descrip { get; set; }
        public string url { get; set; }
        public int idestado { get; set; }
        public Nullable<int> menuPadre { get; set; }
    
        public virtual estado estado { get; set; }
        public virtual ICollection<rol> rol { get; set; }
    }
}
