//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC02a.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class pedido_productos
    {
        [Column("idpedido_productos"), Key]
        public int idpedido_productos { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> total { get; set; }
        public int idpedido { get; set; }
        public int idproducto { get; set; }
    
        public virtual pedido pedido { get; set; }
        public virtual producto producto { get; set; }
    }
}
