//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC02a.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class pedido
    {
        public pedido()
        {
            this.ordenProduccion = new HashSet<ordenProduccion>();
            this.PAGO = new HashSet<PAGO>();
            this.pedido_estados = new HashSet<pedido_estados>();
            this.pedido_productos = new HashSet<pedido_productos>();
            this.Seguimiento = new HashSet<Seguimiento>();
        }
        [Column("idpedido"), Key]
        public int idpedido { get; set; }
        [Required(ErrorMessage = "El Nombre es dato requerido"), StringLength(100)]
        public string contacto_nom { get; set; }
        [Required(ErrorMessage = "El Apellido es dato requerido"), StringLength(100)]
        public string contacto_ape { get; set; }
        [Required(ErrorMessage = "El email es dato requerido"),
       RegularExpression("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$", ErrorMessage = "Formato de email no válido")]
        public string contacto_mail { get; set; }
        public string contacto_fijo { get; set; }
        [Required(ErrorMessage = "El Numero celular es dato requerido"), StringLength(100)]
        public string contacto_movil { get; set; }
        public Nullable<int> tipoentrega { get; set; }

        public Nullable<System.DateTime> fechaPedido { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "La fecha es obligatoria")]
        public Nullable<System.DateTime> fechaentrega { get; set; }
        public Nullable<int> tcomprobante { get; set; }
        public string ruc { get; set; }
        public string razonsocial { get; set; }
        [Required(ErrorMessage = "La direccion es dato requerido"), StringLength(100)]
        public string entrega_dir { get; set; }
        [Required(ErrorMessage = "La urbanizacion es dato requerido"), StringLength(100)]
        public string entrega_urba { get; set; }
        public decimal subTotal { get; set; }
        public decimal igv { get; set; }
        public decimal totalpedido { get; set; }
        public string notas { get; set; }
        public int idCliente { get; set; }
        public int iddistrito { get; set; }
        public int idtipo_compPago { get; set; }
        public int idestado { get; set; }
        public int idtipopago { get; set; }
        public string entrega_ref { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual distrito distrito { get; set; }
        public virtual estado estado { get; set; }
        public virtual ICollection<ordenProduccion> ordenProduccion { get; set; }
        public virtual ICollection<PAGO> PAGO { get; set; }
        public virtual tipo_compPago tipo_compPago { get; set; }
        public virtual TIPO_PAGO TIPO_PAGO { get; set; }
        public virtual ICollection<pedido_estados> pedido_estados { get; set; }
        public virtual ICollection<pedido_productos> pedido_productos { get; set; }
        public virtual ICollection<Seguimiento> Seguimiento { get; set; }
    }
}
