//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC02a.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class pedido_estados
    {
        public int idpedido { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int idestadoPed { get; set; }
    
        public virtual estadoPed estadoPed { get; set; }
        public virtual pedido pedido { get; set; }
    }
}
