//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC02a.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class producto
    {
        public producto()
        {
            this.Carrito = new HashSet<Carrito>();
            this.pedido_productos = new HashSet<pedido_productos>();
            this.insumo = new HashSet<insumo>();
        }
     [Column("idproducto"), Key]
        public int idproducto { get; set; }
     [Required(ErrorMessage = "El Nombre es dato requerido"), StringLength(100)]
     public string nomProducto { get; set; }
     [Required(ErrorMessage = "La descripcion es dato requerido"), StringLength(500)]
     public string descProd { get; set; }
     [Required(ErrorMessage = "El Precio es Requerido"), RegularExpression(@"^\d+(.\d{1,2})?$")]
        public Nullable<decimal> precio { get; set; }
        public string nomFoto { get; set; }
        public int idestado { get; set; }
        public int idcategoriaProd { get; set; }
    
        public virtual ICollection<Carrito> Carrito { get; set; }
        public virtual categoriaProd categoriaProd { get; set; }
        public virtual estado estado { get; set; }
        public virtual ICollection<pedido_productos> pedido_productos { get; set; }
        public virtual ICollection<insumo> insumo { get; set; }
    }
}
