//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC02a.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Seguimiento
    {
        [Column("idSeguimiento"), Key]

        public int idSeguimiento { get; set; }
        public int idpedido { get; set; }
        public int idestado { get; set; }
        public System.DateTime fechacambio { get; set; }
        public int idempleado { get; set; }
        public int idCliente { get; set; }
        public string notas { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual estado estado { get; set; }
        public virtual pedido pedido { get; set; }
    }
}
